# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://j-heffernan.github.io/ii/
title: iNQUISITIVE iPSEITY 
email: julesmheffernan@gmail.com
description: "This designer's story..." # "Write an awesome description for your new site here. 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/julesmh79
  - title: github
    url: https://github.com/j-heffernan/ii
  - title: linkedin
    url: http://www.linkedin.com/in/juliemheffernan/
