# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: iNQUISITIVE iPSEITY
email: julesmhffn@gmail.com
description: > # "Write an awesome description for your new site here. 
  This designer's story..."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/julesmh79
  - title: github
    url: https://github.com/j-heffernan/ii
  - title: linkedin
    url: http://www.linkedin.com/in/juliemheffernan/
